// actionTypes.js
export const FETCH_PRODUCTS_PROGRESS = "FETCH_PRODUCTS_PROGRESS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
